
const DATA=window.APP_DATA, KEY="dominicStageReady2027", MEALS=["Breakfast","Pre-workout","Post-workout","Lunch","Dinner","Snacks"];
const SPLIT={"Breakfast":{protein:35,carbs:65,fat:20},"Pre-workout":{protein:35,carbs:80,fat:10},"Post-workout":{protein:45,carbs:95,fat:8},"Lunch":{protein:35,carbs:60,fat:20},"Dinner":{protein:35,carbs:60,fat:28},"Snacks":{protein:15,carbs:30,fat:14}};
let state=JSON.parse(localStorage.getItem(KEY)||"null")||{workouts:{},daily:{},weights:[],photos:[],cardio:[],posing:[],checkIns:[],settings:{...DATA.dailyTargets,showDate:DATA.showDate},selectedDate:todayISO(),recentFoods:[],mealTargets:structuredClone(SPLIT),supplements:["Creatine","Protein powder","Vitamin D","Magnesium"],peakWeek:{}};
let activeMeal="Breakfast",selectedFood=null,timerInt=null,poseInt=null,scanStream=null,scanFrame=null;
function migrate(){state.workouts||={};state.daily||={};state.weights||=[];state.photos||=[];state.cardio||=[];state.posing||=[];state.checkIns||=[];state.recentFoods||=[];state.supplements||=[];state.peakWeek||={};state.settings={...DATA.dailyTargets,showDate:DATA.showDate,...(state.settings||{})};state.settings.carbs||=390;state.settings.fat||=100;state.mealTargets||=structuredClone(SPLIT);state.selectedDate||=todayISO();Object.values(state.daily).forEach(d=>{d.foods||={};MEALS.forEach(m=>d.foods[m]||=[]);d.recovery||={};d.supplements||={}});save()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function todayISO(){return new Date().toISOString().slice(0,10)} function dObj(s){return new Date(s+"T12:00:00")} function fmt(s){return dObj(s).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})} function dayName(s){return dObj(s).toLocaleDateString(undefined,{weekday:"long"})}
function ensureDaily(date){state.daily[date]||={steps:"",water:"",tasks:{},foods:{},recovery:{},supplements:{}};let d=state.daily[date];d.foods||={};MEALS.forEach(m=>d.foods[m]||=[]);d.recovery||={};d.supplements||={};return d}
function days(a,b){return Math.ceil((dObj(b)-dObj(a))/86400000)}
function phaseFor(date){let show=state.settings.showDate;if(date<"2027-03-08")return"Lean Growth Phase";if(date<"2027-04-12")return"Mini-Cut";if(date<"2027-05-24")return"Final Growth Phase";if(date<show)return"Contest Prep";return date===show?"Show Day":"Post-Show Recovery"}
function render(){renderDashboard();renderWorkout();renderNutrition();renderProgress();renderPrep();renderSettings()}
function renderDashboard(){let date=state.selectedDate,d=ensureDaily(date),show=state.settings.showDate,phase=phaseFor(date);q("dateLabel").textContent=fmt(date);q("phaseTitle").textContent=phase;q("phasePill").textContent=phase;q("countdown").textContent=Math.max(0,days(date,show))+" days until show day";let totals=dayTotals(d),w=latestWeight();q("dashboardStats").innerHTML=stat("Weight",w?`${w.weight} lb`:"—")+stat("Calories",`${round(totals.calories)} / ${state.settings.calories}`)+stat("Protein",`${round1(totals.protein)} / ${state.settings.protein}g`)+stat("Steps",`${d.steps||0} / ${state.settings.steps}`);q("coachRecommendation").innerHTML=coachText();let checks=[["Training",workoutDone(date)],["Nutrition",Math.abs(totals.calories-state.settings.calories)<=state.settings.calories*.08],["Steps",num(d.steps)>=state.settings.steps],["Water",num(d.water)>=state.settings.waterOz],["Recovery",num(d.recovery.sleep)>=7]];q("todayChecklist").innerHTML=checks.map(x=>`<div class="checkitem"><span>${x[0]}</span><b class="${x[1]?'good-text':'muted'}">${x[1]?'Complete':'Open'}</b></div>`).join("")}
function stat(a,b){return `<div class="stat"><span>${a}</span><b>${b}</b></div>`}
function coachText(){let c=state.checkIns.at(-1);if(!c)return"<b>Start with a weekly check-in.</b><p>Log at least 4 weigh-ins, nutrition adherence, hunger and gym performance. The coach will recommend whether to hold or adjust calories.</p>";return `<b>${esc(c.recommendation.title)}</b><p>${esc(c.recommendation.text)}</p><small class="muted">${fmt(c.date)}</small>`}
function renderWorkout(){let date=state.selectedDate,w=DATA.schedule[dayName(date)],root=q("workoutRoot");q("workoutDate").textContent=fmt(date);q("workoutTitle").textContent=w.title;q("workoutFocus").textContent=w.focus;renderWeek();root.innerHTML="";if(!w.exercises.length){(w.recovery||[]).forEach((t,i)=>root.appendChild(checkRow(t,`rec${i}`,ensureDaily(date).tasks)));return}w.exercises.forEach((e,ei)=>{let box=document.createElement("div");box.className="exercise";box.innerHTML=`<div class="exercise-head"><div><b>${esc(e.name)}</b><div class="meta">${e.sets} sets · ${e.reps} · RIR ${e.rir}</div><div class="cue">${esc(e.cue)}</div></div><button class="btn" onclick="startTimer(${e.rest})">Timer</button></div>`;for(let si=0;si<e.sets;si++){let k=`${date}|${ei}|${si}`,v=state.workouts[k]||{},r=document.createElement("div");r.className="setrow";r.innerHTML=`<b>${si+1}</b><label>Weight<input type="number" value="${v.weight??""}" data-k="${k}" data-f="weight"></label><label>Reps<input type="number" value="${v.reps??""}" data-k="${k}" data-f="reps"></label><label>RIR<input type="number" value="${v.rir??""}" data-k="${k}" data-f="rir"></label><input type="checkbox" ${v.done?"checked":""} data-k="${k}" data-f="done">`;box.appendChild(r)}root.appendChild(box)});root.querySelectorAll("input").forEach(i=>i.onchange=()=>{let k=i.dataset.k,f=i.dataset.f;state.workouts[k]||={};state.workouts[k][f]=f==="done"?i.checked:i.value;save();renderWorkout();renderDashboard()});updateWorkoutProgress()}
function renderWeek(){let root=q("weekStrip");root.innerHTML="";let d=dObj(state.selectedDate),dow=(d.getDay()+6)%7,mon=new Date(d);mon.setDate(d.getDate()-dow);for(let i=0;i<7;i++){let x=new Date(mon);x.setDate(mon.getDate()+i);let iso=x.toISOString().slice(0,10),b=document.createElement("button");b.className="daybtn"+(iso===state.selectedDate?" active":"")+(workoutDone(iso)?" done":"");b.innerHTML=`${x.toLocaleDateString(undefined,{weekday:"short"})}<br>${x.getDate()}`;b.onclick=()=>{state.selectedDate=iso;save();render()};root.appendChild(b)}}
function workoutDone(date){let w=DATA.schedule[dayName(date)];if(!w.exercises.length)return false;return w.exercises.every((e,ei)=>Array.from({length:e.sets},(_,si)=>state.workouts[`${date}|${ei}|${si}`]?.done).every(Boolean))}
function updateWorkoutProgress(){let date=state.selectedDate,w=DATA.schedule[dayName(date)],total=w.exercises.reduce((a,e)=>a+e.sets,0),done=0;w.exercises.forEach((e,ei)=>{for(let si=0;si<e.sets;si++)if(state.workouts[`${date}|${ei}|${si}`]?.done)done++});let pct=total?Math.round(done/total*100):0;q("workoutPct").textContent=pct+"%";q("workoutBar").style.width=pct+"%"}
function checkRow(text,key,obj){let r=document.createElement("label");r.className="checkitem";r.innerHTML=`<input type="checkbox" ${obj[key]?"checked":""}><span>${esc(text)}</span>`;r.querySelector("input").onchange=e=>{obj[key]=e.target.checked;save()};return r}
function foodTotals(items){return items.reduce((a,f)=>{let x=num(f.servings)||1;a.calories+=num(f.calories)*x;a.protein+=num(f.protein)*x;a.carbs+=num(f.carbs)*x;a.fat+=num(f.fat)*x;return a},{calories:0,protein:0,carbs:0,fat:0})} function dayTotals(d){return foodTotals(MEALS.flatMap(m=>d.foods[m]||[]))}
function renderNutrition(){let d=ensureDaily(state.selectedDate),t=state.settings,total=dayTotals(d);q("nutritionDate").textContent=fmt(state.selectedDate);setMacro("Calories",total.calories,t.calories,"");setMacro("Protein",total.protein,t.protein,"g");setMacro("Carbs",total.carbs,t.carbs,"g");setMacro("Fat",total.fat,t.fat,"g");let root=q("mealRoot");root.innerHTML="";MEALS.forEach(meal=>{let items=d.foods[meal],mt=state.mealTargets[meal]||{},sum=foodTotals(items),box=document.createElement("div");box.className="card meal-card";let status=mealStatus(sum,mt);box.innerHTML=`<div class="row-between"><div><h3>${meal} <span class="meal-status ${status.cls}">${status.text}</span></h3><div class="muted small">${mt.protein||0}P · ${mt.carbs||0}C · ${mt.fat||0}F target</div></div><div class="right"><b>${round(sum.calories)} cal</b><div class="muted small">${round1(sum.protein)}P · ${round1(sum.carbs)}C · ${round1(sum.fat)}F</div></div></div>`;items.forEach((f,i)=>{let x=num(f.servings)||1,row=document.createElement("div");row.className="food-row";row.innerHTML=`<div><b>${esc(f.name)}</b><div class="muted small">${esc(f.brand||"")} · ${esc(f.servingLabel||"serving")} × ${x}</div></div><div class="right">${round(num(f.calories)*x)} cal<div class="muted small">${round1(num(f.protein)*x)}P · ${round1(num(f.carbs)*x)}C · ${round1(num(f.fat)*x)}F</div></div><button class="icon-btn">×</button>`;row.querySelector("button").onclick=()=>{items.splice(i,1);save();renderNutrition();renderDashboard()};box.appendChild(row)});let a=document.createElement("div");a.className="actions top-gap";a.innerHTML="<button class='btn primary'>+ Add food</button><button class='btn'>Copy</button><button class='btn'>Clear</button>";a.children[0].onclick=()=>openFoodModal(meal);a.children[1].onclick=()=>copyMeal(meal);a.children[2].onclick=()=>{d.foods[meal]=[];save();renderNutrition()};box.appendChild(a);root.appendChild(box)})}
function setMacro(label,value,target,suffix){let key=label.toLowerCase(),rem=round1(target-value);q("macro"+label).textContent=`${round1(value)} / ${target}${suffix}`;q("remaining"+label).textContent=rem>=0?`${rem}${suffix} remaining`:`${Math.abs(rem)}${suffix} over`;let b=q("bar_"+key);b.style.width=Math.min(100,target?value/target*100:0)+"%";b.classList.toggle("over",value>target)}
function mealStatus(s,t){if(!s.calories)return{text:"Planned",cls:""};let ok=["protein","carbs","fat"].every(k=>Math.abs(s[k]-(t[k]||0))/Math.max(1,t[k]||0)<=.12);if(ok)return{text:"On target",cls:"good"};if(["protein","carbs","fat"].some(k=>s[k]>(t[k]||0)*1.15))return{text:"Adjust",cls:"over"};return{text:"In progress",cls:""}}
function redistributeMacros(){let d=ensureDaily(state.selectedDate),tot=dayTotals(d),rem={protein:Math.max(0,state.settings.protein-tot.protein),carbs:Math.max(0,state.settings.carbs-tot.carbs),fat:Math.max(0,state.settings.fat-tot.fat)},empty=MEALS.filter(m=>!d.foods[m].length);if(!empty.length)return alert("No empty meals to redistribute into.");empty.forEach(m=>state.mealTargets[m]={protein:round1(rem.protein/empty.length),carbs:round1(rem.carbs/empty.length),fat:round1(rem.fat/empty.length)});save();renderNutrition();renderSettings()}
function copyMeal(meal){let d=ensureDaily(state.selectedDate),dest=prompt("Copy to: "+MEALS.join(", "),meal);if(MEALS.includes(dest)){d.foods[dest].push(...structuredClone(d.foods[meal]));save();renderNutrition()}}
function copyPreviousDay(){let p=dObj(state.selectedDate);p.setDate(p.getDate()-1);let src=state.daily[p.toISOString().slice(0,10)];if(!src?.foods)return alert("No foods logged yesterday.");ensureDaily(state.selectedDate).foods=structuredClone(src.foods);save();renderNutrition()}
function openFoodModal(meal){activeMeal=meal;selectedFood=null;q("foodMealLabel").textContent="Adding to "+meal;q("foodModal").classList.remove("hidden");q("foodServingEditor").classList.add("hidden");showFoodMode("search",document.querySelector(".segmented button"))}
function closeFoodModal(){stopBarcodeScanner();q("foodModal").classList.add("hidden")} function showFoodMode(mode,btn){document.querySelectorAll(".food-mode").forEach(x=>x.classList.add("hidden"));q("food"+cap(mode)+"Mode").classList.remove("hidden");document.querySelectorAll(".segmented button").forEach(x=>x.classList.remove("active"));btn?.classList.add("active");q("foodServingEditor").classList.add("hidden");if(mode==="recent")renderFoodResults(state.recentFoods,q("recentFoods"))}
async function searchFoods(){let query=q("foodSearchInput").value.trim(),root=q("foodSearchResults");if(query.length<2)return;root.innerHTML="<p class='muted'>Searching…</p>";try{let u=`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(query)}&search_simple=1&action=process&json=1&page_size=25&fields=code,product_name,brands,serving_size,nutriments`,r=await fetch(u),j=await r.json();renderFoodResults((j.products||[]).map(offToFood).filter(f=>f.name&&f.calories),root)}catch{root.innerHTML="<p class='notice'>Search failed. Add it manually.</p>"}}
function renderFoodResults(fs,root){root.innerHTML=fs.length?"":"<p class='muted'>No results.</p>";fs.forEach(f=>{let x=document.createElement("button");x.className="result-item";x.innerHTML=`<b>${esc(f.name)}</b><span>${esc(f.brand||"")} · ${round(f.calories)} cal · ${round1(f.protein)}P</span>`;x.onclick=()=>selectFood(f);root.appendChild(x)})}
function offToFood(p){let n=p.nutriments||{},use=Number.isFinite(Number(n["energy-kcal_serving"]));return{id:uid(),barcode:p.code||"",name:p.product_name||"",brand:p.brands||"",servingLabel:p.serving_size||"100 g",calories:num(use?n["energy-kcal_serving"]:n["energy-kcal_100g"]),protein:num(use?n.proteins_serving:n.proteins_100g),carbs:num(use?n.carbohydrates_serving:n.carbohydrates_100g),fat:num(use?n.fat_serving:n.fat_100g),servings:1,source:"Open Food Facts"}}
function selectFood(f){selectedFood=structuredClone(f);q("selectedFoodName").textContent=f.name;q("selectedFoodMeta").textContent=[f.brand,f.source].filter(Boolean).join(" · ");q("selectedServings").value=1;q("selectedServingLabel").value=f.servingLabel||"1 serving";q("foodServingEditor").classList.remove("hidden");q("selectedServings").oninput=previewFood;previewFood()}
function previewFood(){let x=num(q("selectedServings").value)||1,f=selectedFood;q("selectedFoodMacros").innerHTML=stat("Calories",round(f.calories*x))+stat("Protein",round1(f.protein*x)+"g")+stat("Carbs",round1(f.carbs*x)+"g")+stat("Fat",round1(f.fat*x)+"g")}
function confirmFood(){selectedFood.servings=num(q("selectedServings").value)||1;selectedFood.servingLabel=q("selectedServingLabel").value||"1 serving";ensureDaily(state.selectedDate).foods[activeMeal].push(selectedFood);state.recentFoods=[{...selectedFood,servings:1},...state.recentFoods.filter(x=>x.name!==selectedFood.name)].slice(0,30);save();closeFoodModal();renderNutrition();renderDashboard()}
function addManualFood(){let f={id:uid(),name:val("manualName"),brand:val("manualBrand"),servingLabel:val("manualServing")||"1 serving",calories:num(val("manualCalories")),protein:num(val("manualProtein")),carbs:num(val("manualCarbs")),fat:num(val("manualFat")),source:"Custom"};if(!f.name)return alert("Enter a food name.");selectFood(f)}
async function lookupBarcode(code){code=String(code||q("barcodeInput").value).trim();try{let r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json?fields=code,product_name,brands,serving_size,nutriments`),j=await r.json();if(j.status!==1)throw 0;selectFood(offToFood(j.product));q("barcodeStatus").textContent="Product found."}catch{q("barcodeStatus").textContent="Not found. Add manually."}}
async function startBarcodeScanner(){if(!navigator.mediaDevices?.getUserMedia||!("BarcodeDetector" in window))return q("barcodeStatus").textContent="Camera scanning is unavailable here. Enter the barcode manually.";try{let v=q("barcodeVideo");scanStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});v.srcObject=scanStream;await v.play();let det=new BarcodeDetector();let scan=async()=>{if(!scanStream)return;let c=await det.detect(v).catch(()=>[]);if(c[0]?.rawValue){lookupBarcode(c[0].rawValue);stopBarcodeScanner();return}scanFrame=requestAnimationFrame(scan)};scan()}catch{q("barcodeStatus").textContent="Camera permission failed."}}
function stopBarcodeScanner(){if(scanFrame)cancelAnimationFrame(scanFrame);scanFrame=null;if(scanStream)scanStream.getTracks().forEach(t=>t.stop());scanStream=null}
function addWeight(){let date=val("weightDate"),weight=num(val("weightValue"));if(!date||!weight)return alert("Enter date and weight.");state.weights.push({date,weight,waist:num(val("waistValue")),bodyFat:num(val("bodyFatValue"))});state.weights.sort((a,b)=>a.date.localeCompare(b.date));save();renderProgress();renderDashboard()}
function latestWeight(){return state.weights.at(-1)} function renderProgress(){let rows=q("weightRows");rows.innerHTML=state.weights.slice().reverse().slice(0,15).map((x,i)=>`<div class="checkitem"><span>${fmt(x.date)}<small>${x.waist?` · ${x.waist}" waist`:""}${x.bodyFat?` · ${x.bodyFat}%`:""}</small></span><b>${x.weight} lb</b><button class="btn danger small" onclick="deleteWeight(${state.weights.length-1-i})">Delete</button></div>`).join("");drawChart();q("photoGrid").innerHTML=state.photos.slice().reverse().map((p,i)=>`<figure><img src="${p.data}"><figcaption>${esc(p.pose)} · ${fmt(p.date)}</figcaption></figure>`).join("")}
function deleteWeight(i){state.weights.splice(i,1);save();renderProgress()} function drawChart(){let c=q("weightChart"),ctx=c.getContext("2d"),W=c.clientWidth,H=220,dpr=devicePixelRatio||1;c.width=W*dpr;c.height=H*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,W,H);let a=state.weights.slice(-40);if(a.length<2){ctx.fillStyle="#94a3b8";ctx.fillText("Add at least two weigh-ins.",18,30);return}let min=Math.min(...a.map(x=>x.weight))-1,max=Math.max(...a.map(x=>x.weight))+1;ctx.strokeStyle="#d4af37";ctx.lineWidth=3;ctx.beginPath();a.forEach((x,i)=>{let px=12+i*(W-24)/(a.length-1),py=H-18-(x.weight-min)/(max-min)*(H-36);i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke()}
function addProgressPhoto(input){let f=input.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{state.photos.push({date:val("photoDate")||todayISO(),pose:val("photoPose"),data:r.result});save();renderProgress()};r.readAsDataURL(f)}
function renderPrep(){q("roadmap").innerHTML=[["Now–Mar 7, 2027","Lean growth"],["Mar 8–Apr 11","Mini-cut"],["Apr 12–May 23","Final growth"],["May 24–Sep 17","Contest prep"],["Sep 18, 2027","Show day"]].map(x=>`<div class="checkitem"><b>${x[0]}</b><span>${x[1]}</span></div>`).join("");q("cardioRows").innerHTML=state.cardio.slice().reverse().slice(0,10).map(x=>`<div class="checkitem"><span>${fmt(x.date)} · ${esc(x.type)} · ${esc(x.intensity)}</span><b>${x.minutes} min</b></div>`).join("");q("posingRows").innerHTML=state.posing.slice().reverse().slice(0,8).map(x=>`<div class="checkitem"><span>${fmt(x.date)}</span><b>${x.minutes} min</b></div>`).join("");let d=ensureDaily(state.selectedDate),r=d.recovery;["sleep","quality","hunger","fatigue","stress"].forEach(f=>{let e=q("recovery"+cap(f));e.value=r[f]??"";e.onchange=()=>{r[f]=e.value;save();renderDashboard()}});["steps","water"].forEach(f=>{let e=q("daily_"+f);e.value=d[f]??"";e.onchange=()=>{d[f]=e.value;save();renderDashboard()}});q("supplementList").innerHTML=state.supplements.map((s,i)=>`<label class="checkitem"><input type="checkbox" ${d.supplements[s]?"checked":""} onchange="toggleSupplement('${escAttr(s)}',this.checked)"><span>${esc(s)}</span><button class="icon-btn" onclick="removeSupplement(${i});event.preventDefault()">×</button></label>`).join("");renderPeakWeek()}
function addCardio(){state.cardio.push({date:state.selectedDate,minutes:num(val("cardioMinutes")),type:val("cardioType"),intensity:val("cardioIntensity"),notes:val("cardioNotes")});save();renderPrep()} function startPosing(min){stopPosing();let left=min*60;q("posingTimer").textContent=`${min}:00`;poseInt=setInterval(()=>{left--;q("posingTimer").textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,"0")}`;if(left<=0){stopPosing();state.posing.push({date:state.selectedDate,minutes:min});save();renderPrep();alert("Posing session complete.")}},1000)} function stopPosing(){clearInterval(poseInt);poseInt=null}
function addSupplement(){let s=val("newSupplement");if(s&&!state.supplements.includes(s)){state.supplements.push(s);q("newSupplement").value="";save();renderPrep()}} function removeSupplement(i){state.supplements.splice(i,1);save();renderPrep()} function toggleSupplement(s,v){ensureDaily(state.selectedDate).supplements[s]=v;save()}
function renderPeakWeek(){let root=q("peakWeekGrid"),show=dObj(state.settings.showDate);root.innerHTML="";for(let i=6;i>=0;i--){let d=new Date(show);d.setDate(show.getDate()-i);let iso=d.toISOString().slice(0,10),p=state.peakWeek[iso]||={};let x=document.createElement("div");x.className="peak-day";x.innerHTML=`<b>${i===0?"Show day":d.toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"})}</b><label>Meals / carbs notes<textarea>${esc(p.meals||"")}</textarea></label><label>Training / posing<textarea>${esc(p.training||"")}</textarea></label><label>Water & sodium consistency<textarea>${esc(p.water||"")}</textarea></label>`;x.querySelectorAll("textarea").forEach((t,j)=>t.onchange=()=>{p[["meals","training","water"][j]]=t.value;save()});root.appendChild(x)}}
function openCheckIn(){q("checkInModal").classList.remove("hidden");let w=latestWeight();q("ciWeight").value=w?.weight||"";q("ciWaist").value=w?.waist||""} function closeCheckIn(){q("checkInModal").classList.add("hidden")}
function saveCheckIn(){let c={date:todayISO(),weight:num(val("ciWeight")),waist:num(val("ciWaist")),adherence:num(val("ciAdherence")),performance:num(val("ciPerformance")),hunger:num(val("ciHunger")),recovery:num(val("ciRecovery"))},prev=state.checkIns.at(-1),phase=phaseFor(todayISO()),rec={title:"Hold targets",text:"Keep calories and macros unchanged for another week."};if(c.adherence<85)rec={title:"Improve adherence first",text:"Do not adjust calories yet. Hit the current targets more consistently before interpreting scale changes."};else if(prev){let change=c.weight-prev.weight;if(phase.includes("Growth")&&change<.2)rec={title:"Small calorie increase",text:"Consider adding 100–150 calories, primarily from carbohydrates, because weight gain is below target."};if(phase.includes("Growth")&&change>.8)rec={title:"Slow the gain",text:"Consider reducing 100–150 calories to limit unnecessary fat gain."};if((phase==="Mini-Cut"||phase==="Contest Prep")&&change>-.3)rec={title:"Increase the deficit slightly",text:"Consider reducing 100–150 calories or adding a small amount of cardio."};if((phase==="Mini-Cut"||phase==="Contest Prep")&&change<-1.8)rec={title:"Deficit may be too aggressive",text:"Consider adding 100–150 calories to protect performance and lean mass."}}if(c.performance<0&&c.recovery<=2)rec={title:"Prioritize recovery",text:"Hold calories for now, reduce fatigue, and consider a deload before making the diet more aggressive."};c.recommendation=rec;state.checkIns.push(c);save();q("checkInResult").innerHTML=`<div class="notice top-gap"><b>${rec.title}</b><p>${rec.text}</p></div>`;renderDashboard()}
function renderSettings(){["calories","protein","carbs","fat","steps","waterOz","showDate"].forEach(f=>{let e=q("set_"+f);e.value=state.settings[f];e.onchange=()=>{state.settings[f]=f==="showDate"?e.value:num(e.value);save();render()}});let root=q("mealTargetSettings");root.innerHTML="";MEALS.forEach(m=>{let t=state.mealTargets[m],r=document.createElement("div");r.className="meal-target-row";r.innerHTML=`<b>${m}</b><label>P<input type="number" value="${t.protein}" data-f="protein"></label><label>C<input type="number" value="${t.carbs}" data-f="carbs"></label><label>F<input type="number" value="${t.fat}" data-f="fat"></label>`;r.querySelectorAll("input").forEach(i=>i.onchange=()=>{t[i.dataset.f]=num(i.value);save();renderNutrition()});root.appendChild(r)})}
function startTimer(sec){clearInterval(timerInt);let left=sec;q("timerBox").classList.remove("hidden");let tick=()=>{q("timerText").textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,"0")}`;if(left--<=0){stopTimer();alert("Rest complete.")}};tick();timerInt=setInterval(tick,1000)} function stopTimer(){clearInterval(timerInt);q("timerBox").classList.add("hidden")}
function switchTab(id,btn){const target=q(id);if(!target)return;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===target));document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));if(btn)btn.classList.add("active");localStorage.setItem(KEY+"ActiveTab",id);window.scrollTo({top:0,behavior:"smooth"});if(id==="progressTab")setTimeout(drawChart,30)}
function restoreActiveTab(){const id=localStorage.getItem(KEY+"ActiveTab")||"dashboardTab",target=q(id)||q("dashboardTab"),btn=[...document.querySelectorAll("nav button")].find(b=>b.getAttribute("onclick")?.includes(`'${target.id}'`));document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===target));document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===btn));if(target.id==="progressTab")setTimeout(drawChart,30)}
function exportData(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="stage-ready-backup.json";a.click()} function importData(i){let f=i.files[0],r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);migrate();render()}catch{alert("Invalid backup.")}};r.readAsText(f)} function resetAll(){if(confirm("Delete all app data?")){localStorage.removeItem(KEY);location.reload()}}
function q(id){return document.getElementById(id)} function val(id){return q(id).value.trim()} function num(x){let n=Number(x);return Number.isFinite(n)?n:0} function round(x){return Math.round(num(x))} function round1(x){return Math.round(num(x)*10)/10} function uid(){return crypto.randomUUID?.()||String(Date.now()+Math.random())} function cap(s){return s[0].toUpperCase()+s.slice(1)} function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))} function escAttr(s){return String(s).replace(/'/g,"\\'")}
migrate();q("weightDate").value=todayISO();q("photoDate").value=todayISO();render();restoreActiveTab();
